// This class provides a way of generating a spectrum given user-defined
// parameters. A spectrum is generated by summing up a series of Gaussian
// distributions defined on the spectrum curve. Each Gaussian represents a peak
// in the spectral, which typically correlates with a specific element or
// material type.

#ifndef SRC_SPECTRUM_SPECTRUM_GENERATOR_H_
#define SRC_SPECTRUM_SPECTRUM_GENERATOR_H_

#include <vector>

namespace hsi_data_generator {

// The distribution variables for a single spectrum peak. These values encode a
// Gaussian distribution that represents a single peak in the spectrum. All
// values should be normalized between 0 and 1.
struct PeakDistribution {
  // The position is the x-position of the peak. The peak will be centered at
  // this position. It is the mean of the Guassian.
  //
  // Position should be normalized between 0 and 1.
  double peak_position;

  // The amplitude is the "height" of the peak. 0 is nothing, 1 is the maximum
  // height.
  double amplitude;

  // The width is the standard deviation of the Gaussian, and encodes how thin
  // or thick the peak will be. Sharp, instantaneous peaks should have a small
  // width.
  //
  // A peak's width should be smaller than the span of the entire spectrum,
  // which is a normalized width of 1.0.
  double width;
};

class SpectrumGenerator {
 public:
  explicit SpectrumGenerator(const int num_bands) : num_bands_(num_bands) {}

  void AddPeak(const PeakDistribution& peak);

  std::vector<double> GetNormalizedSpectrum() const;

 private:
  // The number of bands that this spectrum will span.
  const int num_bands_;

  std::vector<PeakDistribution> peaks_;
};

}  // namespace hsi_data_generator

#endif  // SRC_SPECTRUM_SPECTRUM_GENERATOR_H_
